### ISSUE TITLE
error trying to run the bot

### ISSUE THREAD

**Issue by gamees** [Fytex/Instagram-Giveaways-Winner#4]
i'm trying to run the bot first time and i get this error, how to fix ?

6 Getting Default Adapter failed.
Traceback (most recent call last):
  File "script.py", line 95, in <module>
    bot.log_in(username, password)
  File "F:\arquivos dudu\Script instagram 2\modules\instagram_bot.py", line 55, in log_in
    self.driver.find_element_by_css_selector('div[role=dialog] button ').click()
  File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Richard\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div[role=dialog] button "}
  (Session info: chrome=86.0.4240.111)
  (Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.17763 x86_64)

**Comment by victorprince** [comment]
I am also getting the same error.

**Comment by Fytex** [comment]
If you open https://www.instagram.com in google chrome's incognito mode (ctrl + shift + n) does a popup (as shown in the image) appear?
![image](https://user-images.githubusercontent.com/25065248/97779482-46a15080-1b76-11eb-96c6-d67e1b670565.png)

**Comment by gamees** [comment]
no

**Comment by Fytex** [comment]
Could you try now? @gamees

**Comment by Fytex** [comment]
Well since it appears to be working I'll close this thread.

**Comment by MisterJalil** [comment]
> If you open https://www.instagram.com in google chrome's incognito mode (ctrl + shift + n) does a popup (as shown in the image) appear?
> 
> @gamees @victorprince ![image](https://user-images.githubusercontent.com/25065248/97779482-46a15080-1b76-11eb-96c6-d67e1b670565.png)

This happens to me, and I don't have the cookie folder
